# Change these first
owner: CirclesUBI # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Circles Indonesia Dashboard
    url: https://dashboard.circlesubi.id
  - name: Circles Indonesia Translations
    url: https://translations.circlesubi.id


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.circlesubi.id
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/30386623
  name: CirclesUBI Indonesia
  introTitle: "Welcome to the CirclesUBI Indonesia status page."
  introMessage: Here you find information about the current status of the CirclesUBI Indonesia services.
  navbar:
    - title: Status
      href: /
    - title: App
      href: https://app.circlesubi.id

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
