# Change these first
owner: CirclesUBI
repo: status-indonesia

sites:
  - name: App
    url: https://app.circlesubi.id
  - name: API
    url: https://api.circlesubi.id
  - name: Indexer
    url: https://rpc.circlesubi.id/indexer
  - name: Pathfinder
    url: https://rpc.circlesubi.id/pathfinder

assignees:
  - almereyda
  - jaensen

status-website:
  cname: status.circlesubi.id
  favicon: https://app.circlesubi.id/apple-touch-icon.png
  faviconSvg: https://cdn.jsdelivr.net/gh/CirclesUBI/o-platform/shell/public/logos/circles.svg
  logoUrl: https://avatars.githubusercontent.com/u/30386623
  name: "CirclesUBI Indonesia"
  introTitle: "Welcome to the CirclesUBI Indonesia status page."
  introMessage: "Here you find information about the current status of the CirclesUBI Indonesia services."
  navbar:
    - title: Status
      href: /
    - title: App
      href: https://app.circlesubi.id

runner: "[circles-ubuntu-8-32-300, linux]"
user-agent: CirclesUBI-Status-App
